/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.converterapp;

import java.awt.Color;
/*
 *
 * @author Admin
 */
public class Close extends javax.swing.JFrame {
    public Close(){
        initComponents();
        Color backgroundcolor=new Color(255,255,255);
        this.getContentPane().setBackground(backgroundcolor);
        setVisible(true);      
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closethank = new javax.swing.JLabel();
        closeyou = new javax.swing.JLabel();
        closeforusing = new javax.swing.JLabel();
        closethe = new javax.swing.JLabel();
        closeconverterapp = new javax.swing.JLabel();
        Projectby = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Closing Window");
        setLocation(new java.awt.Point(10, 10));
        setSize(new java.awt.Dimension(720, 520));

        closethank.setFont(new java.awt.Font("Baskerville Old Face", 1, 90)); // NOI18N
        closethank.setForeground(new java.awt.Color(0, 0, 102));
        closethank.setText("THANK");
        closethank.setToolTipText("");

        closeyou.setFont(new java.awt.Font("Baskerville Old Face", 1, 90)); // NOI18N
        closeyou.setForeground(new java.awt.Color(0, 0, 102));
        closeyou.setText("YOU");

        closeforusing.setFont(new java.awt.Font("Baskerville Old Face", 1, 85)); // NOI18N
        closeforusing.setForeground(new java.awt.Color(0, 0, 102));
        closeforusing.setText("FOR USING");

        closethe.setFont(new java.awt.Font("Baskerville Old Face", 1, 85)); // NOI18N
        closethe.setForeground(new java.awt.Color(0, 0, 102));
        closethe.setText("THE");

        closeconverterapp.setFont(new java.awt.Font("Arial", 1, 75)); // NOI18N
        closeconverterapp.setForeground(new java.awt.Color(0, 0, 102));
        closeconverterapp.setText("CONVERTER APP");

        Projectby.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        Projectby.setForeground(new java.awt.Color(0, 0, 0));
        Projectby.setText("Project By Irfan Abidi (Irfan7014)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(closethank))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(closeyou)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(closethe))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(closeconverterapp)))
                .addGap(0, 34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(closeforusing)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Projectby)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closethank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeyou)
                .addGap(20, 20, 20)
                .addComponent(closeforusing)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closethe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeconverterapp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Projectby)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Close.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Close.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Close.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Close.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Close().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Projectby;
    private javax.swing.JLabel closeconverterapp;
    private javax.swing.JLabel closeforusing;
    private javax.swing.JLabel closethank;
    private javax.swing.JLabel closethe;
    private javax.swing.JLabel closeyou;
    // End of variables declaration//GEN-END:variables
}
