/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.converterapp;

import java.awt.Color;

/**
 *
 * @author Admin
 */
public class ConvertTemp extends javax.swing.JFrame {

    /**
     * Creates new form ConvertTemp
     */
    public ConvertTemp() {
        initComponents();
        Color backgroundcolor=new Color(255,102,102);
        this.getContentPane().setBackground(backgroundcolor);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entertempjLabel = new javax.swing.JLabel();
        temptext = new javax.swing.JTextField();
        fromunitjLabel = new javax.swing.JLabel();
        fromunit = new javax.swing.JComboBox();
        tounitjLabel = new javax.swing.JLabel();
        tounit = new javax.swing.JComboBox();
        convertbutton = new javax.swing.JButton();
        resetbutton = new javax.swing.JButton();
        closebutton = new javax.swing.JButton();
        convertedtemp = new javax.swing.JTextField();
        gotohomepagebutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONVERT TEMPERATURE");

        entertempjLabel.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        entertempjLabel.setForeground(new java.awt.Color(0, 0, 0));
        entertempjLabel.setText("ENTER TEMPERATURE: ");

        temptext.setBackground(new java.awt.Color(255, 255, 255));
        temptext.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        fromunitjLabel.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        fromunitjLabel.setForeground(new java.awt.Color(0, 0, 0));
        fromunitjLabel.setText("FROM UNIT:");

        fromunit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        fromunit.setForeground(new java.awt.Color(0, 0, 0));
        fromunit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kelvin", "Celsius", "Farenheit" }));

        tounitjLabel.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        tounitjLabel.setForeground(new java.awt.Color(0, 0, 0));
        tounitjLabel.setText("TO UNIT: ");

        tounit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tounit.setForeground(new java.awt.Color(0, 0, 0));
        tounit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kelvin", "Celsius", "Farenheit" }));

        convertbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        convertbutton.setForeground(new java.awt.Color(0, 0, 0));
        convertbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/converterapp/reload.png"))); // NOI18N
        convertbutton.setText("CONVERT");
        convertbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convertbuttonMouseClicked(evt);
            }
        });

        resetbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        resetbutton.setForeground(new java.awt.Color(0, 0, 0));
        resetbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/converterapp/cancel.png"))); // NOI18N
        resetbutton.setText("RESET");
        resetbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetbuttonMouseClicked(evt);
            }
        });

        closebutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        closebutton.setForeground(new java.awt.Color(0, 0, 0));
        closebutton.setText("CLOSE");
        closebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebuttonMouseClicked(evt);
            }
        });

        convertedtemp.setBackground(new java.awt.Color(255, 255, 255));
        convertedtemp.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        gotohomepagebutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        gotohomepagebutton.setForeground(new java.awt.Color(0, 0, 0));
        gotohomepagebutton.setText("GO BACK TO HOME PAGE");
        gotohomepagebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotohomepagebuttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tounitjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fromunitjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(entertempjLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fromunit, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temptext, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tounit, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(convertedtemp)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(convertbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(resetbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(closebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gotohomepagebutton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entertempjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temptext, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromunitjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromunit, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tounitjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tounit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convertbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(convertedtemp, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(gotohomepagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetbuttonMouseClicked
        // TODO add your handling code here:
        dispose();
        ConvertTemp ct=new ConvertTemp();
    }//GEN-LAST:event_resetbuttonMouseClicked

    private void closebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonMouseClicked
        // TODO add your handling code here:
        dispose();
        Close c=new Close();
    }//GEN-LAST:event_closebuttonMouseClicked

    private void convertbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertbuttonMouseClicked
        // TODO add your handling code here:
        String from,to,ans,convert;
        from=fromunit.getSelectedItem().toString();
        to=tounit.getSelectedItem().toString();
        convert=temptext.getText();
        if (from.equals("Kelvin") && to.equals("Kelvin"))   //1
        {
            ans=kelvintokelvin(convert);
            convertedtemp.setText(convert+" K = "+ans+" K");
        }
        else if(from.equals("Kelvin") && to.equals("Celsius"))   //2
        {
            ans=kelvintocelsius(convert);
            convertedtemp.setText(convert+" K = "+ans+" °C");
        }
        else if(from.equals("Kelvin") && to.equals("Farenheit"))   //3
        {
            ans=kelvintofarenheit(convert);
            convertedtemp.setText(convert+" K = "+ans+" °F");
        }
        else if(from.equals("Celsius") && to.equals("Kelvin"))   //4
        {
            ans=celsiustokelvin(convert);
            convertedtemp.setText(convert+" °C = "+ans+" K");
        }
        else if(from.equals("Celsius") && to.equals("Celsius"))   //5
        {
            ans=celsiustocelsius(convert);
            convertedtemp.setText(convert+" °C = "+ans+" °C");
        }
        else if(from.equals("Celsius") && to.equals("Farenheit"))   //6
        {
            ans=celsiustofarenheit(convert);
            convertedtemp.setText(convert+" °C = "+ans+" °F");
        }
        else if(from.equals("Farenheit") && to.equals("Kelvin"))   //7
        {
            ans=farenheittokelvin(convert);
            convertedtemp.setText(convert+" °F = "+ans+" K");
        }
        else if(from.equals("Farenheit") && to.equals("Celsius"))   //8
        {
            ans=farenheittocelsius(convert);
            convertedtemp.setText(convert+" °F = "+ans+" °C");
        }
        else if(from.equals("Farenheit") && to.equals("Farenheit"))   //9
        {
            ans=farenheittofarenheit(convert);
            convertedtemp.setText(convert+" °F = "+ans+" °F");
        }
    }//GEN-LAST:event_convertbuttonMouseClicked

    private void gotohomepagebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotohomepagebuttonMouseClicked
        // TODO add your handling code here:
        dispose();
        Start s=new Start();
    }//GEN-LAST:event_gotohomepagebuttonMouseClicked

    /**
     * @param val
     * @return 
     */
    public String kelvintokelvin(String val)  //1) K to K
    {
        return val;
    }
    public String celsiustocelsius(String val)  //2) °C to °C
    {
        return val;
    }
    public String farenheittofarenheit(String val)  //3) °F to °F
    {
        return val;
    }
    public String kelvintocelsius(String val)  //4) K to °C
    {
        String ans=val;
        double input=Double.parseDouble(val);
        ans=Double.toString(input-273.15);
        return ans;
    }
    public String kelvintofarenheit(String val)  //5) K to °F
    {
        String ans=val;
        double input=Double.parseDouble(val);
        ans=Double.toString(((input-273.15)*1.8)+32);
        return ans;
    }
    public String celsiustokelvin(String val)  //6) °C to K
    {
        String ans=val;
        double input=Double.parseDouble(val);
        ans=Double.toString(input+273.15);
        return ans;
    }
    public String celsiustofarenheit(String val)  //7) °C to °F
    {
        String ans=val;
        double input=Double.parseDouble(val);
        ans=Double.toString((input*1.8)+32);
        return ans;
    }
    public String farenheittocelsius(String val)  //8) °F to °C
    {
        String ans=val;
        double input=Double.parseDouble(val);
        ans=Double.toString((input-32)*5/9);
        return ans;
    }
    public String farenheittokelvin(String val)  //9) °F to K
    {
        String ans=val;
        double input=Double.parseDouble(val);
        ans=Double.toString((input-32)*5/9+273.15);
        return ans;
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvertTemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvertTemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvertTemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvertTemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvertTemp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closebutton;
    private javax.swing.JButton convertbutton;
    private javax.swing.JTextField convertedtemp;
    private javax.swing.JLabel entertempjLabel;
    private javax.swing.JComboBox fromunit;
    private javax.swing.JLabel fromunitjLabel;
    private javax.swing.JButton gotohomepagebutton;
    private javax.swing.JButton resetbutton;
    private javax.swing.JTextField temptext;
    private javax.swing.JComboBox tounit;
    private javax.swing.JLabel tounitjLabel;
    // End of variables declaration//GEN-END:variables
}
