/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.converterapp;

import java.awt.Color;

/**
 *
 * @author Admin
 */
public class StartTimeConverting extends javax.swing.JFrame {

    /**
     * Creates new form StartTimeConverting
     */
    public StartTimeConverting() {
        initComponents();
        Color backgroundcolor=new Color(0,0,0);
        this.getContentPane().setBackground(backgroundcolor);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeconvertjLabel = new javax.swing.JLabel();
        converterjLabel = new javax.swing.JLabel();
        timeicon = new javax.swing.JLabel();
        startconvertbutton = new javax.swing.JButton();
        goackbutton = new javax.swing.JButton();
        exitbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        timeconvertjLabel.setFont(new java.awt.Font("Baskerville Old Face", 1, 60)); // NOI18N
        timeconvertjLabel.setForeground(new java.awt.Color(51, 204, 255));
        timeconvertjLabel.setText("TIME");

        converterjLabel.setFont(new java.awt.Font("Baskerville Old Face", 1, 60)); // NOI18N
        converterjLabel.setForeground(new java.awt.Color(51, 204, 255));
        converterjLabel.setText("CONVERTER");

        timeicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\timeconvert.jpg")); // NOI18N

        startconvertbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        startconvertbutton.setForeground(new java.awt.Color(51, 204, 255));
        startconvertbutton.setText("START CONVERTING");
        startconvertbutton.setBorder(null);
        startconvertbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startconvertbuttonMouseClicked(evt);
            }
        });

        goackbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        goackbutton.setForeground(new java.awt.Color(51, 204, 255));
        goackbutton.setText("GO BACK!");
        goackbutton.setBorder(null);
        goackbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goackbuttonMouseClicked(evt);
            }
        });

        exitbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        exitbutton.setForeground(new java.awt.Color(51, 204, 255));
        exitbutton.setText("EXIT");
        exitbutton.setBorder(null);
        exitbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbuttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(timeconvertjLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(converterjLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(timeicon, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(exitbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(goackbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(startconvertbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timeconvertjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(converterjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeicon, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startconvertbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goackbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startconvertbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startconvertbuttonMouseClicked
        // TODO add your handling code here:
        dispose();
        ConvertTime ct=new ConvertTime();
    }//GEN-LAST:event_startconvertbuttonMouseClicked

    private void goackbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goackbuttonMouseClicked
        // TODO add your handling code here:
        dispose();
        Start s=new Start();
    }//GEN-LAST:event_goackbuttonMouseClicked

    private void exitbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbuttonMouseClicked
        // TODO add your handling code here:
        dispose();
        Close c=new Close();
    }//GEN-LAST:event_exitbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartTimeConverting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartTimeConverting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartTimeConverting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartTimeConverting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartTimeConverting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel converterjLabel;
    private javax.swing.JButton exitbutton;
    private javax.swing.JButton goackbutton;
    private javax.swing.JButton startconvertbutton;
    private javax.swing.JLabel timeconvertjLabel;
    private javax.swing.JLabel timeicon;
    // End of variables declaration//GEN-END:variables
}
