/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.converterapp;

import java.awt.Color;

/**
 *
 * @author Admin
 */
public class StartTempConverting extends javax.swing.JFrame {

    /**
     * Creates new form StartTempConverting
     */
    public StartTempConverting() {
        initComponents();
        Color backgroundcolor=new Color(0,0,0);
        this.getContentPane().setBackground(backgroundcolor);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempjLabel = new javax.swing.JLabel();
        converterjLabel = new javax.swing.JLabel();
        tempicon = new javax.swing.JLabel();
        startconvertingbutton = new javax.swing.JButton();
        gobackbutton = new javax.swing.JButton();
        exitbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tempjLabel.setFont(new java.awt.Font("Baskerville Old Face", 1, 60)); // NOI18N
        tempjLabel.setForeground(new java.awt.Color(51, 204, 255));
        tempjLabel.setText("TEMPERATURE");

        converterjLabel.setFont(new java.awt.Font("Baskerville Old Face", 1, 60)); // NOI18N
        converterjLabel.setForeground(new java.awt.Color(51, 204, 255));
        converterjLabel.setText("CONVERTER");

        tempicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\tem.png")); // NOI18N

        startconvertingbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        startconvertingbutton.setForeground(new java.awt.Color(51, 204, 255));
        startconvertingbutton.setText("START CONVERTING");
        startconvertingbutton.setBorder(null);
        startconvertingbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startconvertingbuttonMouseClicked(evt);
            }
        });

        gobackbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        gobackbutton.setForeground(new java.awt.Color(51, 204, 255));
        gobackbutton.setText("GO BACK!");
        gobackbutton.setBorder(null);
        gobackbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gobackbuttonMouseClicked(evt);
            }
        });

        exitbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        exitbutton.setForeground(new java.awt.Color(51, 204, 255));
        exitbutton.setText("EXIT");
        exitbutton.setBorder(null);
        exitbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbuttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(tempjLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(converterjLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(tempicon))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(gobackbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startconvertingbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tempjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(converterjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tempicon)
                .addGap(18, 18, 18)
                .addComponent(startconvertingbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gobackbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gobackbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gobackbuttonMouseClicked
        // TODO add your handling code here:
        dispose();
        Start s=new Start();
    }//GEN-LAST:event_gobackbuttonMouseClicked

    private void exitbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbuttonMouseClicked
        // TODO add your handling code here:
        dispose();
        Close c=new Close();
    }//GEN-LAST:event_exitbuttonMouseClicked

    private void startconvertingbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startconvertingbuttonMouseClicked
        // TODO add your handling code here:
        dispose();
        ConvertTemp ct=new ConvertTemp();
    }//GEN-LAST:event_startconvertingbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartTempConverting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartTempConverting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartTempConverting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartTempConverting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartTempConverting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel converterjLabel;
    private javax.swing.JButton exitbutton;
    private javax.swing.JButton gobackbutton;
    private javax.swing.JButton startconvertingbutton;
    private javax.swing.JLabel tempicon;
    private javax.swing.JLabel tempjLabel;
    // End of variables declaration//GEN-END:variables
}
