/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.converterapp;

import java.awt.Color;

/**
 *
 * @author Admin
 */
public class StartLengthConverting extends javax.swing.JFrame {

    /**
     * Creates new form StartLengthConverting
     */
    public StartLengthConverting() {
        initComponents();
        Color backgroundcolor=new Color(0,0,0);
        this.getContentPane().setBackground(backgroundcolor);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lengthjLabel = new javax.swing.JLabel();
        convertingjLabel = new javax.swing.JLabel();
        lengthicon = new javax.swing.JLabel();
        startconvertbutton = new javax.swing.JButton();
        gobackbutton = new javax.swing.JButton();
        exitbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lengthjLabel.setFont(new java.awt.Font("Baskerville Old Face", 1, 60)); // NOI18N
        lengthjLabel.setForeground(new java.awt.Color(51, 204, 255));
        lengthjLabel.setText("LENGTH");

        convertingjLabel.setFont(new java.awt.Font("Baskerville Old Face", 1, 60)); // NOI18N
        convertingjLabel.setForeground(new java.awt.Color(51, 204, 255));
        convertingjLabel.setText("CONVERTER");

        lengthicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\lengthconvert.png")); // NOI18N

        startconvertbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        startconvertbutton.setForeground(new java.awt.Color(51, 204, 255));
        startconvertbutton.setText("START CONVERTING");
        startconvertbutton.setBorder(null);
        startconvertbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startconvertbuttonMouseClicked(evt);
            }
        });

        gobackbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        gobackbutton.setForeground(new java.awt.Color(51, 204, 255));
        gobackbutton.setText("GO BACK!");
        gobackbutton.setBorder(null);
        gobackbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gobackbuttonMouseClicked(evt);
            }
        });

        exitbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        exitbutton.setForeground(new java.awt.Color(51, 204, 255));
        exitbutton.setText("EXIT");
        exitbutton.setBorder(null);
        exitbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbuttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(convertingjLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(lengthjLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(lengthicon))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(exitbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(startconvertbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(gobackbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lengthjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convertingjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lengthicon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startconvertbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gobackbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gobackbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gobackbuttonMouseClicked
        // TODO add your handling code here:
        dispose();
        Start s=new Start();
    }//GEN-LAST:event_gobackbuttonMouseClicked

    private void exitbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbuttonMouseClicked
        // TODO add your handling code here:
        dispose();
        Close c=new Close();
    }//GEN-LAST:event_exitbuttonMouseClicked

    private void startconvertbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startconvertbuttonMouseClicked
        // TODO add your handling code here:
        dispose();
        ConvertLength cl=new ConvertLength();
    }//GEN-LAST:event_startconvertbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartLengthConverting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartLengthConverting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartLengthConverting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartLengthConverting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartLengthConverting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel convertingjLabel;
    private javax.swing.JButton exitbutton;
    private javax.swing.JButton gobackbutton;
    private javax.swing.JLabel lengthicon;
    private javax.swing.JLabel lengthjLabel;
    private javax.swing.JButton startconvertbutton;
    // End of variables declaration//GEN-END:variables
}
