/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.converterapp;

import java.awt.Color;

/**
 *
 * @author Admin
 */
public class StartMassConverting extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public StartMassConverting() {
        initComponents();
        Color backgroundcolor=new Color(0,0,0);
        this.getContentPane().setBackground(backgroundcolor);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        massjLabel = new javax.swing.JLabel();
        converterjLabel = new javax.swing.JLabel();
        weighticon = new javax.swing.JLabel();
        startconvertbutton = new javax.swing.JButton();
        exitbuton = new javax.swing.JButton();
        gobackbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome To Weight Converter");
        setBackground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(10, 10));
        setSize(new java.awt.Dimension(600, 600));

        massjLabel.setFont(new java.awt.Font("Baskerville Old Face", 1, 60)); // NOI18N
        massjLabel.setForeground(new java.awt.Color(51, 204, 255));
        massjLabel.setText("MASS");

        converterjLabel.setFont(new java.awt.Font("Baskerville Old Face", 1, 60)); // NOI18N
        converterjLabel.setForeground(new java.awt.Color(51, 204, 255));
        converterjLabel.setText("CONVERTER");

        weighticon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\weightconvert.png")); // NOI18N

        startconvertbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        startconvertbutton.setForeground(new java.awt.Color(51, 204, 255));
        startconvertbutton.setText(" START CONVERTING ");
        startconvertbutton.setBorder(null);
        startconvertbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startconvertbuttonMouseClicked(evt);
            }
        });

        exitbuton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        exitbuton.setForeground(new java.awt.Color(51, 204, 255));
        exitbuton.setText("  EXIT  ");
        exitbuton.setBorder(null);
        exitbuton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbutonMouseClicked(evt);
            }
        });

        gobackbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        gobackbutton.setForeground(new java.awt.Color(51, 204, 255));
        gobackbutton.setText("GO BACK!");
        gobackbutton.setBorder(null);
        gobackbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gobackbuttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(exitbuton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gobackbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(startconvertbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(converterjLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(weighticon))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(massjLabel)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(massjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(converterjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weighticon, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startconvertbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gobackbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitbuton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startconvertbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startconvertbuttonMouseClicked
        // TODO add your handling code here:
        ConvertMass cw=new ConvertMass();
        dispose();
    }//GEN-LAST:event_startconvertbuttonMouseClicked

    private void exitbutonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbutonMouseClicked
        // TODO add your handling code here:
        dispose();
        Close c=new Close();
    }//GEN-LAST:event_exitbutonMouseClicked

    private void gobackbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gobackbuttonMouseClicked
        // TODO add your handling code here:
        dispose();
        Start s=new Start();
    }//GEN-LAST:event_gobackbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartMassConverting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartMassConverting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartMassConverting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartMassConverting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartMassConverting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel converterjLabel;
    private javax.swing.JButton exitbuton;
    private javax.swing.JButton gobackbutton;
    private javax.swing.JLabel massjLabel;
    private javax.swing.JButton startconvertbutton;
    private javax.swing.JLabel weighticon;
    // End of variables declaration//GEN-END:variables
}
