/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.converterapp;

import java.awt.Color;

/**
 *
 * @author Admin
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
        Color backgroundcolor=new Color(255,187,187);
        this.getContentPane().setBackground(backgroundcolor);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lengthjLabel = new javax.swing.JLabel();
        massjLabel = new javax.swing.JLabel();
        timejLabel = new javax.swing.JLabel();
        tempjLabel = new javax.swing.JLabel();
        convertlengthbutton = new javax.swing.JButton();
        javax.swing.JButton convertmassbutton = new javax.swing.JButton();
        converttimebutton = new javax.swing.JButton();
        converttempbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Start");
        setLocation(new java.awt.Point(10, 10));

        lengthjLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\lengthconvert.png")); // NOI18N

        massjLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\weightconvert.png")); // NOI18N

        timejLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\timeconvert.jpg")); // NOI18N

        tempjLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\tem.png")); // NOI18N

        convertlengthbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        convertlengthbutton.setForeground(new java.awt.Color(0, 0, 0));
        convertlengthbutton.setText("CONVERT LENGTH");
        convertlengthbutton.setToolTipText("");
        convertlengthbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convertlengthbuttonMouseClicked(evt);
            }
        });

        convertmassbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        convertmassbutton.setForeground(new java.awt.Color(0, 0, 0));
        convertmassbutton.setText("CONVERT MASS");
        convertmassbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convertmassbuttonMouseClicked(evt);
            }
        });

        converttimebutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        converttimebutton.setForeground(new java.awt.Color(0, 0, 0));
        converttimebutton.setText("CONVERT TIME");
        converttimebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                converttimebuttonMouseClicked(evt);
            }
        });

        converttempbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        converttempbutton.setForeground(new java.awt.Color(0, 0, 0));
        converttempbutton.setText("CONVERT TEMPERATURE");
        converttempbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                converttempbuttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(convertlengthbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                        .addComponent(convertmassbutton)
                        .addGap(114, 114, 114)
                        .addComponent(converttimebutton)
                        .addGap(116, 116, 116)
                        .addComponent(converttempbutton)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lengthjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(massjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tempjLabel)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempjLabel)
                    .addComponent(timejLabel)
                    .addComponent(massjLabel)
                    .addComponent(lengthjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(convertlengthbutton)
                    .addComponent(convertmassbutton)
                    .addComponent(converttimebutton)
                    .addComponent(converttempbutton))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertmassbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertmassbuttonMouseClicked
        // TODO add your handling code here:
        dispose();
        StartMassConverting smc=new StartMassConverting();
        
    }//GEN-LAST:event_convertmassbuttonMouseClicked

    private void converttempbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_converttempbuttonMouseClicked
        // TODO add your handling code here:
        dispose();
        StartTempConverting stc=new StartTempConverting();
    }//GEN-LAST:event_converttempbuttonMouseClicked

    private void convertlengthbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertlengthbuttonMouseClicked
        // TODO add your handling code here:
        dispose();
        StartLengthConverting slc=new StartLengthConverting();
    }//GEN-LAST:event_convertlengthbuttonMouseClicked

    private void converttimebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_converttimebuttonMouseClicked
        // TODO add your handling code here:
        dispose();
        StartTimeConverting stc=new StartTimeConverting();
    }//GEN-LAST:event_converttimebuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convertlengthbutton;
    private javax.swing.JButton converttempbutton;
    private javax.swing.JButton converttimebutton;
    private javax.swing.JLabel lengthjLabel;
    private javax.swing.JLabel massjLabel;
    private javax.swing.JLabel tempjLabel;
    private javax.swing.JLabel timejLabel;
    // End of variables declaration//GEN-END:variables
}
